name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Setup golangci-lint
      uses: golangci/golangci-lint-action@v2.5.2
    - name: Run make all
      run: make all
